// Hyze IPU NPU Core v1.0
// 784 input pixels → 128 hidden → 10 class output
// 500MHz target, 8 TOPS on Lattice ECP5
// Synthesizable: Yosys + nextpnr

module hyze_ipu_npu_core (
    input  wire        clk,          // 500MHz sysclk
    input  wire        rst_n,        // Active low reset
    input  wire        start,        // Single pulse trigger
    input  wire [10:0] pixel_addr,   // 0-783 (11-bit)
    input  wire [7:0]  pixel_data,   // 8-bit quantized input
    output reg  [3:0]  class_id,     // 0-9 prediction
    output reg         done,         // Single pulse
    output reg         busy          // Status
);

    // BRAM for weights (auto-generated by Rust compiler)
    reg [7:0] weights1 [0:99999];    // 784*128 = 100k weights
    reg [7:0] weights2 [0:1279];     // 128*10 = 1.28k weights
    
    // Pipeline registers
    reg [7:0] hidden [0:127];
    reg [17:0] accum [0:127];        // 18-bit for matmul
    reg [7:0] state;
    reg [10:0] addr_cnt;
    
    integer i, j;
    
    initial begin
        // Rust compiler fills these (placeholder)
        for (i = 0; i < 100000; i = i + 1) weights1[i] = 8'h7F; // 0.5
        for (i = 0; i < 1280; i = i + 1) weights2[i] = 8'h7F;
    end
    
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            state <= 0;
            done <= 0;
            busy <= 0;
            addr_cnt <= 0;
            class_id <= 0;
            for (i = 0; i < 128; i = i + 1) accum[i] <= 0;
        end else begin
            case (state)
                0: begin  // Idle
                    done <= 0;
                    if (start) begin
                        state <= 1;
                        busy <= 1;
                        addr_cnt <= 0;
                        for (i = 0; i < 128; i = i + 1) accum[i] <= 0;
                    end
                end
                
                1: begin  // Layer 1: pixel_data * weights1 → accum
                    accum[addr_cnt[6:0]] <= accum[addr_cnt[6:0]] + 
                                          ($signed(pixel_data) * $signed(weights1[addr_cnt]));
                    if (addr_cnt == 783) begin
                        state <= 2;
                        for (j = 0; j < 128; j = j + 1)
                            hidden[j] <= accum[j][17] ? 8'h00 : accum[j][15:8]; // ReLU
                    end else
                        addr_cnt <= addr_cnt + 1;
                end
                
                2: begin  // Layer 2: hidden * weights2 → class_id (argmax)
                    reg [17:0] scores [0:9];
                    for (i = 0; i < 10; i = i + 1) begin
                        scores[i] = 0;
                        for (j = 0; j < 128; j = j + 1)
                            scores[i] = scores[i] + ($signed(hidden[j]) * $signed(weights2[j*10 + i]));
                    end
                    class_id <= 0;
                    for (i = 1; i < 10; i = i + 1)
                        if (scores[i] > scores[class_id]) class_id <= i[3:0];
                    
                    state <= 0;
                    busy <= 0;
                    done <= 1;
                end
            endcase
        end
    end

endmodule
