use onnx::{Model, GraphProto, NodeProto};
use std::fs::File;
use std::io::Write;

pub fn compile_onnx_to_verilog(onnx_path: &str, verilog_path: &str) -> anyhow::Result<()> {
    let model = onnx::load_model(onnx_path)?;
    let graph = model.graph.as_ref().unwrap();
    
    // Extract weights from ONNX Constant nodes
    let mut weights1 = Vec::new(); // 784*128
    let mut weights2 = Vec::new(); // 128*10
    
    for node in &graph.node {
        if node.op_type == "Constant" {
            if node.name.contains("weight1") {
                weights1 = extract_tensor_data(&node.attribute[0].t.as_ref().unwrap())?;
            }
        }
    }
    
    // Generate Verilog weights array
    let mut v = File::create(verilog_path)?;
    writeln!(v, "// Auto-generated by Hyze IPU Rust Compiler")?;
    writeln!(v, "reg [7:0] weights1 [0:{}] = {{", (weights1.len() - 1))?;
    
    for (i, &w) in quantize_int8(&weights1).iter().enumerate() {
        write!(v, "8'h{:02x}", w)?;
        if i % 16 == 15 { writeln!(v, ",")?; }
    }
    writeln!(v, "}};")?;
    
    println!("Compiled {} → {} weights", onnx_path, verilog_path);
    Ok(())
}

fn quantize_int8(f32_weights: &[f32]) -> Vec<u8> {
    let scale = 127.0 / f32_weights.iter().map(|&x| x.abs()).sum::<f32>() * f32_weights.len() as f32;
    f32_weights.iter().map(|&x| ((x * scale).clamp(-128.0, 127.0) + 128.0) as u8).collect()
}
